route:
  repeat_interval: 20h
  receiver: 'Mail Alert'
  routes:
   - match:
       severity: 'critical'   
     receiver: 'Mail Alert'
     #group_by: [ alertname ]
     repeat_interval: 3m
     group_wait: 15s
     group_interval: 15s
     continue: true
  #  - match:
  #      severity: 'critical'
  #      team: 'survey'   
  #    receiver: 'Survey Team'
  #    #group_by: [ alertname ]
  #    repeat_interval: 3m
  #    group_wait: 15s
  #    group_interval: 15s
  #    continue: true
   - match:
       severity: 'critical'
       team: 'athmanirbar'   
     receiver: 'Athmanirbar Team'
     #group_by: [ alertname ]
     repeat_interval: 3m
     group_wait: 15s
     group_interval: 15s
     continue: true
   - match:
       severity: 'action_required'
       team : 'openmetadata'
     receiver: 'Infrastructure Support Team'
     #group_by: [ alertname ]
     repeat_interval: 3m
     group_wait: 15s
     group_interval: 15s
     continue: true
receivers:
  - name: 'Mail Alert'
    email_configs:
      - smarthost: 'smtp.office365.com:587'
        auth_username: 'noreply@elait.com'
        auth_password: "xjlzhkgvfccbvysm"
        from: 'noreply@elait.com'
        to: 'kugan.muthalrayan@elait.com,napa.vekshanth@elait.com,christopher.leslin@elait.com,korrakuti.vinitha@elait.com,supriya.accha@elait.com,dhinesh.eswaran@elait.com,sathyasri.ganesh@elait.com,shahul.syed@elait.com,ravindran.govindaraj@elait.com,bala.subramanian@elait.onmicrosoft.com,'
        headers:
          subject: '{{ if eq .Status "firing" }} [FIRING] Grafana Alerts {{ else if eq .Status "resolved" }} [RESOLVED] Grafana Alerts {{end}}'
        send_resolved: true
  # - name: 'Survey Team'
  #   email_configs:
  #     - smarthost: 'smtp.office365.com:587'
  #       auth_username: 'noreply@elait.com'
  #       auth_password: "xjlzhkgvfccbvysm"
  #       from: 'noreply@elait.com'
  #       to: 'achutha.karunanithi@elait.com'
  #       headers:
  #         subject: '{{ if eq .Status "firing" }} [FIRING] Grafana Alerts {{ else if eq .Status "resolved" }} [RESOLVED] Grafana Alerts {{end}}'
  #       send_resolved: true
  - name: 'Athmanirbar Team'
    email_configs:
      - smarthost: 'smtp.office365.com:587'
        auth_username: 'noreply@elait.com'
        auth_password: "xjlzhkgvfccbvysm"
        from: 'noreply@elait.com'
        to: 'nivedha.madhavan@elait.com,nandhieswaran.s@elait.com,raji.kumar@elait.com,mutyala.dileep@elait.com,bharath.vedarasu@elait.com'
        headers:
          subject: '{{ if eq .Status "firing" }} [FIRING] Grafana Alerts {{ else if eq .Status "resolved" }} [RESOLVED] Grafana Alerts {{end}}'
        send_resolved: true
  - name: 'Infrastructure Support Team'
    email_configs:
      - smarthost: 'smtp.office365.com:587'
        auth_username: 'noreply@elait.com'
        auth_password: "xjlzhkgvfccbvysm"
        from: 'noreply@elait.com'
        to: 'kugan.muthalrayan@elait.com,christopher.leslin@elait.com,napa.vekshanth@elait.com,dhinesh.eswaran@elait.com,sathyasri.ganesh@elait.com'
        headers:
          subject: '{{ if eq .Status "firing" }} [FIRING] Grafana Alerts {{ else if eq .Status "resolved" }} [RESOLVED] Grafana Alerts {{end}}'
        send_resolved: true
