#Original Developer           - Kugan 
#Creation date                - 11/03/2024
#Current Developer            - Kugan
#Last Modified                - 11/03/2024
#Title                        - Database Services
#Description                  - This script has the alert rules for SIT , UAT And PROD

####################### SIT & UAT Database Service ######################
groups:
  - name: Databases_SIT
    rules:
      - alert: Postgres_Database_SIT
        expr: absent(container_start_time_seconds{name="databases-postgres-1"})
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "Postgres_Database_SIT_Service down"
          description: "Postgres_Database_SIT_Service container is down for more than 30 seconds."

      - alert: Mongo_Database_SIT
        expr: absent(container_start_time_seconds{name="databases-mongo-1"})
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "Mongo_Database_SIT_Service down"
          description: "Mongo_Database_SIT_Service container is down for more than 30 seconds."
      
      - alert: MSSQL_Database_SIT
        expr: absent(container_start_time_seconds{name="databases-mssql-2019-1"})
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "MSSQL_Database_SIT_Service down"
          description: "MSSQL_Database_SIT_Service container is down for more than 30 seconds."

####################### PROD Database Service #####################
  - name: Databases_PROD
    rules:
      - alert: Postgres_Database_PROD
        expr: absent(container_start_time_seconds{name="datbases-postgres-1"})
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "Postgres_Database_PROD_Service down"
          description: "Postgres_Database_PROD_Service container is down for more than 30 seconds."

      - alert: Mongo_Database_SIT
        expr: absent(container_start_time_seconds{name="datbases-mongo-1"})
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "Mongo_Database_PROD_Service down"
          description: "Mongo_Database_PROD_Service container is down for more than 30 seconds."
      
      - alert: MSSQL_Database_SIT
        expr: absent(container_start_time_seconds{name="datbases-mssql-2019-1"})
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "MSSQL_Database_PROD_Service down"
          description: "MSSQL_Database_PROD_Service container is down for more than 30 seconds."
