#Original Developer           - Kugan 
#Creation date                - 11/03/2024
#Current Developer            - Kugan
#Last Modified                - 11/03/2024
#Title                        - Nginx Application
#Description                  - This script has the alert rules for SIT, UAT And PROD
groups:
  - name: Nginx_Applications
    rules:
      - alert: Nginx_Application_SIT
        expr: absent(container_start_time_seconds{name="nginx_proxy"})
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "Nginx_Application_SIT_Service down"
          description: "Nginx_Application_SIT_Service container is down for more than 30 seconds."

      - alert: Nginx_Application_PROD
        expr: absent(container_start_time_seconds{name="nginx_prod"})
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "Nginx_Application_PROD_Service down"
          description: "Nginx_Application_PROD_Service container is down for more than 30 seconds."
    
