#Original Developer           - Kugan 
#Creation date                - 11/03/2024
#Current Developer            - Kugan
#Last Modified                - 11/03/2024
#Title                        - Project_Tracking Application
#Description                  - This script has the alert rules for SIT, UAT And PROD
groups:
  - name: Project_Tracking_Applications
    rules:
      - alert: Project_Tracking_Application_SIT
        expr: absent(container_start_time_seconds{name="pt-pt-sit-1"})
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "Project_Tracking_Application_SIT_Service down"
          description: "Project_Tracking_Application_SIT_Service container is down for more than 30 seconds."

      - alert: Project_Tracking_Application_UAT
        expr: absent(container_start_time_seconds{name="pt-pt-uat-1"})
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "Project_Tracking_Application_UAT_Service down"
          description: "Project_Tracking_Application_UAT_Service container is down for more than 30 seconds."
    
      - alert: Project_Tracking_Application_PROD
        expr: absent(container_start_time_seconds{name="pt_management-pt-prod-1"})
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "Project_Tracking_Application_PROD_Service down"
          description: "Project_Tracking_Application_PROD_Service container is down for more than 30 seconds."        
