#prometheus.yml - file
#this must be in the same directory as of docker-compose.yml file

rule_files:
  - host_server_rules.yml
  - athmanirbar_application_rules.yml
  - rbac_application_rules.yml
  - survey_application_rules.yml
  - elait_in_rules.yml
  - survey_creator_rules.yml
  - databases_rules.yml
  - project_tracking_rules.yml
  - nginx_rules.yml
  - open_metadata_rules.yml

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: [ 'instance-1:9093' ]


    
scrape_configs:
- job_name: cadvisor
  scrape_interval: 5s
  static_configs:
  - targets:
    - instance-1:2001
    - prod-instance:2001

- job_name: node_exporter
  scrape_interval: 5s
  static_configs:
  - targets:
    - instance-1:9100
    - prod-instance:9100

- job_name: prometheus
  scrape_interval: 5s
  static_configs:
  - targets:
    - instance-1:2003

