#Original Developer           - Kugan 
#Creation date                - 11/03/2024
#Current Developer            - Kugan
#Last Modified                - 11/03/2024
#Title                        - Survey_Creator Application
#Description                  - This script has the alert rules for SIT
groups:
  - name: Survey_Creator_Applications
    rules:
      - alert: Survey_Creator_Application_SIT
        expr: absent(container_start_time_seconds{name="survey-creator-survey-creator-sit-1"})
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "Survey_Creator_Application_SIT_Service down"
          description: "Survey_Creator_Application_SIT_Service container is down for more than 30 seconds."

      - alert: Survey_Creator_Application_UAT
        expr: absent(container_start_time_seconds{name="survey-creator-survey-creator-uat-1"})
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "Survey_Creator_Application_UAT_Service down"
          description: "Survey_Creator_Application_UAT_Service container is down for more than 30 seconds."
