#Original Developer           - Kugan 
#Creation date                - 11/03/2024
#Current Developer            - Kugan
#Last Modified                - 11/03/2024
#Title                        - Survey Application
#Description                  - This script has the alert rules for SIT , UAT And PROD
groups:
  - name: Survey_Applications
    rules:
      - alert: Survey_Application_SIT
        expr: absent(container_start_time_seconds{name="dg-assessment-dg-assessment-sit-1"})
        for: 30s
        labels:
          severity: critical
          team : survey
        annotations:
          summary: "Survey_Application_SIT_Service down"
          description: "Survey_Application_SIT_Service container is down for more than 30 seconds."

      - alert: Survey_Application_UAT
        expr: absent(container_start_time_seconds{name="survey_2-survey2-uat-1"})
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "Survey_Application_UAT_Service down"
          description: "Survey_Application_UAT_Service container is down for more than 30 seconds."
      
      - alert: Survey_Application_PROD
        expr: absent(container_start_time_seconds{name="dg-assessment-dg-assessment-prod-1"})
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "Survey_Application_PROD_Service down"
          description: "Survey_Application_PROD_Service container is down for more than 30 seconds."
